version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/workspace

  web:
    image: nginx:1.18-alpine
    ports:
      - 8000:80
    volumes:
      - ./src:/workspace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir:
      /workspace

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
